# Generated by Django 2.2.3 on 2019-07-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdat',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
