# Generated by Django 2.2.3 on 2019-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190716_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdat',
            name='upvote_ratio',
            field=models.CharField(max_length=10),
        ),
    ]
