# Generated by Django 2.2.3 on 2019-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190716_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdat',
            name='id',
            field=models.CharField(max_length=110, primary_key=True, serialize=False),
        ),
    ]
