# Generated by Django 2.2.3 on 2019-07-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190716_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='hot',
            fields=[
                ('time', models.CharField(max_length=80)),
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='top',
            fields=[
                ('time', models.CharField(max_length=80)),
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
            ],
        ),
    ]
