# Generated by Django 2.2.3 on 2019-07-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_hot_top'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hot',
            new_name='whosHot',
        ),
        migrations.RenameModel(
            old_name='top',
            new_name='whosTop',
        ),
    ]
