Copy ..\virginFiles\doing.csv ..\reader1
Copy ..\virginFiles\doing.csv ..\reader2
Copy ..\virginFiles\doing.csv ..\reader3
Copy ..\virginFiles\doing.csv ..\reader4
Copy ..\virginFiles\doing.csv ..\reader5
Copy ..\virginFiles\doing.csv ..\reader6
Copy ..\virginFiles\doing.csv ..\reader7
Copy ..\virginFiles\doing.csv ..\reader8
Copy ..\virginFiles\doing.csv ..\reader9
Copy ..\virginFiles\doing.csv ..\reader10
Copy ..\virginFiles\doing.csv ..\reader11
Copy ..\virginFiles\doing.csv ..\reader12
Copy ..\virginFiles\doing.csv ..\reader13
Copy ..\virginFiles\doing.csv ..\reader14
Copy ..\virginFiles\doing.csv ..\reader15
Copy ..\virginFiles\doing.csv ..\reader16
Copy ..\virginFiles\doing.csv ..\reader17
Copy ..\virginFiles\doing.csv ..\reader18
Copy ..\virginFiles\done.csv ..\reader1
Copy ..\virginFiles\done.csv ..\reader2
Copy ..\virginFiles\done.csv ..\reader3
Copy ..\virginFiles\done.csv ..\reader4
Copy ..\virginFiles\done.csv ..\reader5
Copy ..\virginFiles\done.csv ..\reader6
Copy ..\virginFiles\done.csv ..\reader7
Copy ..\virginFiles\done.csv ..\reader8
Copy ..\virginFiles\done.csv ..\reader9
Copy ..\virginFiles\done.csv ..\reader10
Copy ..\virginFiles\done.csv ..\reader11
Copy ..\virginFiles\done.csv ..\reader12
Copy ..\virginFiles\done.csv ..\reader13
Copy ..\virginFiles\done.csv ..\reader14
Copy ..\virginFiles\done.csv ..\reader15
Copy ..\virginFiles\done.csv ..\reader16
Copy ..\virginFiles\done.csv ..\reader17
Copy ..\virginFiles\done.csv ..\reader18
Copy ..\virginFiles\post.csv ..\reader1
Copy ..\virginFiles\post.csv ..\reader2
Copy ..\virginFiles\post.csv ..\reader3
Copy ..\virginFiles\post.csv ..\reader4
Copy ..\virginFiles\post.csv ..\reader5
Copy ..\virginFiles\post.csv ..\reader6
Copy ..\virginFiles\post.csv ..\reader7
Copy ..\virginFiles\post.csv ..\reader8
Copy ..\virginFiles\post.csv ..\reader9
Copy ..\virginFiles\post.csv ..\reader10
Copy ..\virginFiles\post.csv ..\reader11
Copy ..\virginFiles\post.csv ..\reader12
Copy ..\virginFiles\post.csv ..\reader13
Copy ..\virginFiles\post.csv ..\reader14
Copy ..\virginFiles\post.csv ..\reader15
Copy ..\virginFiles\post.csv ..\reader16
Copy ..\virginFiles\post.csv ..\reader17
Copy ..\virginFiles\post.csv ..\reader18